### PR TITLE
Update Chinese simplified localizations

### PR DESCRIPTION
**Pull request by KuroNoSeiHai**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by MairwunNx — APPROVED** [review]
Great work 😉, Thanks! Changes will included in 2.0.1.

**Comment by KuroNoSeiHai** [comment]
Thanks, I will pull into 14.4 tomorrow. And could you update server-only localisations and gitbook.io, the instructions of essential is for 1.0+version. We don't know the all commands and permissions for 2.0+ version.

**Comment by MairwunNx** [comment]
Of course, new documentation will placed in projectessentials.github.io, currently I works on it.

**Comment by KuroNoSeiHai** [comment]
Thank you. How about server-only essential-localizations? It can't support zh_cn and 2.0+version.

**Comment by MairwunNx** [comment]
Two ways to enable server-side-only localization:
- Manual, through configuration (`general.properties`) find the property `v2-localization-enabled` and change his value to `true`.
- In-game, through command, `/configure-essentials v2-locali... <press tab> set true` (no requires restart)

**Comment by MairwunNx** [comment]
After configuring by manual variant server needs restarts.
After configuring by command you can just type any command to see correct out.

**Comment by MairwunNx** [comment]
You can also configure any module through `/configure-<...>`, you can see all variants with `tab` key.

**Comment by KuroNoSeiHai** [comment]
Thank you. I will try it. Thanks for your responds.

**Comment by MairwunNx** [comment]
Of course!

**Comment by MairwunNx** [comment]
@KuroNoSeiHai have a nice day, I created site, you can see docs at this https://projectessentials.github.io, if any thing will still not understands, you know where ask about it 😉

**Comment by KuroNoSeiHai** [comment]
Thanks! Could you give the discord link?

**Comment by MairwunNx** [comment]
Sure! You can see that in the readme (updated today).

Best regards, Pavel.

**Comment by KuroNoSeiHai** [comment]
Joined it. Thanks a lot.

**Pull request merged**
